routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/get-posts', 'HomeController@getPosts');
Route::get('confirm/{token}/{email}','UserController@index');
Route::post('user/change-password','UserController@changePassword');
Route::resource('user', 'UserController');


Route::get('redirect', 'SocialAuthFacebookController@redirect');
Route::get('callback', 'SocialAuthFacebookController@callback');

Route::get('/get-url','PostController@getURL');
Route::post('/post/{id}','PostController@updatePost');
Route::resource('post', 'PostController');
Route::resource('category', 'CategoryController');

Route::get('all-comments/{post}', 'CommentController@showComments');
Route::resource('comments', 'CommentController');

Route::prefix('admin')->group(function () {
    Route::get('/', 'AdminController@index');
    Route::get('notification', 'AdminController@notification');
    Route::get('users', 'AdminController@users');
    Route::get('update-admin', 'AdminController@updateAdmin');
    Route::get('posts', 'AdminController@posts');
    Route::get('categories', 'AdminController@categories');
    Route::get('comments', 'AdminController@comments');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = ['author_id', 'category_id', 'title', 'img', 'body'];

    public function category()
    {
        return $this->hasOne('App\Category', 'id', 'category_id');
    }

    public function user()
    {
        return $this->hasOne('App\User', 'id', 'author_id');
    }

    public function comments()
    {
        return $this->hasMany('App\Comment');
    }




}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Http\helper;
use Faker\Provider\Image;
use Illuminate\Http\Request;
use App\Http\Requests\UpdatePostRequest;
use App\Http\Requests\StorePostRequest;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Input;
use App\Post;
use App\Category;
use App\Comment;
use App\User;
use Illuminate\Support\Facades\Storage;

class PostController extends Controller
{

    /**
     * Get author posts
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user();
        $posts = Post::where('author_id', $user->id)->get();
        $posts->load('category', 'comments', 'user');
        return response()->json($posts);
    }

    /**
     * Go to create post page -- Add Post
     *
     * @return \Illuminate\Http\Response

     **/

    public function create()
    {
      //
    }

    /**
     * Add new post
     *
     * @param StorePostRequest|Request $request
     * @return \Illuminate\Http\Response
     */

    public function store(StorePostRequest $request)
    {
        $data = $request->all();
        if($request->file('img')){
            $img_name = $request->file('img')->hashName();
            $upload = $request->file('img')->move('img/posts', $img_name);
            if($upload){
                $create_data = [
                    'author_id' => Auth::user()->id,
                    'category_id' => $data['category'],
                    'title' => $data['title'],
                    'body' => $data['body'],
                    'img' => $img_name
                ];

                $post = Post::create($create_data);
                if($post){
                    return response()->json('status', 200);
                }
            }
        }
    }

    /**
     * Show the post
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
       $post = Post::find($id)->load('category', 'user');
        return response()->json($post);
    }

    /**
     * Show the form for editing post.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $helper = new helper;
        $categories_data = $helper->selectCategories();

        $post = Post::find($id);
        return view('post.edit',compact('post', 'categories_data'));
    }

    /**
     * Update the post in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

    }

    /**
     * Remove the post from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function destroy($id)
    {
        $request = request();
        $post = Post::find($id);
        $del = File::delete(public_path('img/posts/' . $post->img));
        if ($del) {
            $delete = $post->delete();
            if ($delete) {
                return response(['msg' => 'Post deleted'], 200);
            }
        }
    }
    public function updatePost(Request $request)
    {
        $data = $request->all();
        $post_data = Post::find($data['id']);
        if($post_data){
            $post_img = $post_data['img'];
            $file = Storage::disk('public')->exists($post_img);
            if ($request->hasFile('img')){

                if($file){
                    File::delete(public_path('img/posts/' . $post_img));
                }
                $name = $request->file('img')->hashName();
                $move = $request->file('img')->move('img/posts',$name);
                if($move){
                    $post_img = $name;
                } else {
                    return response('error', 301);
                }
            } else {
                $post_img = $post_data['img'];
            }
            $edit_data = [
                'author_id' => Auth::user()->id,
                'category_id' => $data['category'],
                'title' => $data['title'],
                'body' => $data['body'],
                'img' => $post_img,
            ];
            $update = Post::find($data['id'])->update($edit_data);
            if ($update) {
                return response('post updated', 200);
            }
        }
    }

}

resources/views/post/create.blade.php
@extends('layouts.app')

@section('content')
    <section id="add-post">
        <div class="theme-menu post">
            <div class="container text-center padding-45">
                <div class="add d-inline">
                    Add Post
                </div>
            </div>
        </div>

        <div class="alert-div {{  session('status') }}"></div>

        <div class="container padding-30 margin-30">
            <form action="{{ route('post.store') }}" method="POST" enctype="multipart/form-data">

                {{ csrf_field() }}

                <div class="form-group{{ $errors->has('post_title') ? ' has-error' : '' }}">
                    <label for="title">Title:</label>
                    <input type="text" class="form-control" id="title" name="title" value="{{ old('title') }}">


                    @if ($errors->has('title'))
                        <span class="help-block">
                             <strong>{{ $errors->first('title') }}</strong>
                        </span>
                    @endif

                </div>

                <div class="form-group{{ $errors->has('post_img') ? ' has-error' : '' }}">
                    <label for="post-img">Image:</label>
                    <input type="file" class="form-control" id="post-img" name="img" value="{{ old('img') }}">

                    @if ($errors->has('img'))
                        <span class="help-block">
                            <strong>{{ $errors->first('img') }}</strong>
                        </span>
                    @endif

                </div>

                <div class="form-group{{ $errors->has('posts') ? ' has-error' : '' }}">
                    <label for="body">Content:</label>
                    <textarea class="form-control" id="body" name="body">{{ old('body') }}</textarea>

                    @if ($errors->has('content'))
                        <span class="help-block">
                            <strong>{{ $errors->first('body') }}</strong>
                        </span>
                    @endif

                </div>
                <div class="form-group">

                    <label for="category">Select Category:</label>
                    {!! Form::select('category', $categories_data, null,['id' => 'category','class' => 'form-control']) !!}
                </div>

                <button class="btn-red" type="submit">Add Post</button>

            </form>
        </div>
    </section>
@endsection

resources/views/post/edit.blade.php
@extends('layouts.app')

@section('content')

    <section id="edit-post">
        <div class="theme-menu post">
            <div class="container text-center padding-45">
                <div class="add d-inline">
                    Edit Post
                </div>
            </div>
        </div>
        @if (session('status'))
            <div class="alert alert-success">
                {{ session('status') }}
            </div>
        @endif
        <div class="container padding-30 margin-30">
            <form action="{{ route('post.update',$post['id']) }}" method="POST" enctype="multipart/form-data">
                <input type="hidden" name="_method" value="put">
                {{ csrf_field() }}

                <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                    <label for="title">Title:</label>
                    <input type="text" class="form-control" id="title" name="title" value="{{ $post['title'] }}">

                </div>

                <div class="form-group{{ $errors->has('img') ? ' has-error' : '' }} edit-img">
                    <label for="post-img" class="d-block">Image:</label>
                    <img src="/img/posts/{{ $post['img'] }}" >
                    <input type="file" class="form-control" id="post-img" name="img" value="{{ old('img') }}">

                </div>

                <div class="form-group">
                    <label for="category">Select Category:</label>
                    {!! Form::select('categories', $categories_data, $post['category_id'],['id' => 'category','class' => 'form-control']) !!}
                </div>

                <div class="form-group{{ $errors->has('post') ? ' has-error' : '' }}">

                    <label for="body">Content:</label>
                    <textarea class="form-control" id="body" name="body">{{ $post['body'] }}</textarea>

                </div>

                <button class="btn-red" type="submit">Edit Post</button>

            </form>
        </div>
    </section>
@endsection

resources/views/post/show.blade.php
@extends('layouts.app')



@section('content')
    @if(session('status') == 'comment-added')
        <script>
            toastr.success("Comment successfully added!");
        </script>
    @endif

    {{--<div class="alert-div {{ session('status') }}"></div>--}}
    <section>
        <div class="theme-menu">
            <div class="container text-center padding-45">
                <div class="my d-inline ">
                    {{ $post['category']['name'] }}
                </div>
            </div>
        </div>
        <div class="container">
            <div class="post-author margin-10-0">
                <img src="/img/users/{{ $post['user']['avatar'] }}" alt="User avatar">
                <a href="{{ route('user.show',$post['user']['id']) }}">{{ $post['user']['name'] }} {{ $post['user']['surname'] }}</a>
            </div>
            <div class="post-title">
                <h2 class="d-inline">{{ $post['title'] }}</h2>
                <a class="post-title-a" href="{{ $post['category']['id'] }}"></a>
            </div>
            <div class="post-time">
                {{ $post['created_at'] }}
            </div>
            <div class="row">
                <div class="post-img col-4">
                    <img src="/img/posts/{{ $post['img'] }}">
                </div>
                <div class="col-8">
                    <p>{{ $post['body'] }}</p>
                </div>
            </div>
            <div id="comment">
                <span><b>Comments</b></span>
                <div class="row">
                    @if(Auth::check())
                        <add-comment :parent-id="parentId"></add-comment>
                        <view-comments  :comments="comments"></view-comments>
                    @else
                        <div class="alert alert-info">
                            <strong>Attention!</strong> For add  or read comments, please Log In or Sign Up.
                        </div>
                    @endif

                </div>
            </div>
        </div>
    </section>
@endsection
@section('scripts')
    <script>
        $('.theme-menu').css({ "background":"url('../img/categories/{{ $post->category->img }}') no-repeat",
        "background-size":"cover"
        });
        localStorage.setItem('post-id',{{$post->id}});

    </script>
@endsection