routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/get-posts', 'HomeController@getPosts');
Route::get('confirm/{token}/{email}','UserController@index');
Route::post('user/change-password','UserController@changePassword');
Route::resource('user', 'UserController');


Route::get('redirect', 'SocialAuthFacebookController@redirect');
Route::get('callback', 'SocialAuthFacebookController@callback');

Route::get('/get-url','PostController@getURL');
Route::post('/post/{id}','PostController@updatePost');
Route::resource('post', 'PostController');
Route::resource('category', 'CategoryController');

Route::get('all-comments/{post}', 'CommentController@showComments');
Route::resource('comments', 'CommentController');

Route::prefix('admin')->group(function () {
    Route::get('/', 'AdminController@index');
    Route::get('notification', 'AdminController@notification');
    Route::get('users', 'AdminController@users');
    Route::get('update-admin', 'AdminController@updateAdmin');
    Route::get('posts', 'AdminController@posts');
    Route::get('categories', 'AdminController@categories');
    Route::get('comments', 'AdminController@comments');
});

resources/views/admin/categories.blade.php
 @extends('layouts.admin')

@section('content')
    {{--@if (session()->has('type'))--}}
         {{--<div class="alert alert-info">{{ session('type') }}</div>--}}
        {{--<div class="alert alert-info">{{ session()->get('message') }}</div>--}}
    {{--@endif--}}
    <div class="col-9">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header card-header-info">
                        <h4 class="card-title mt-0">Categories Table</h4>
                        <p class="card-category"> Here is a subtitle for this table</p>
                    </div>
                    <div class="card-body">
                        <div class="add-category float-right margin-10-0">
                            <button class="btn btn-success" data-toggle="modal" data-target="#add">Add category</button>
                        </div>
                        <div class="table-responsive">
                            <table class="table">
                                <thead class=" text-info">
                                <th>
                                    ID
                                </th>
                                <th>
                                    Name
                                </th>
                                <th>
                                    Image
                                </th>
                                <th>
                                    Date
                                </th>
                                <th>
                                    Delete
                                </th>
                                </thead>
                                <tbody id="categories">
                                    @foreach($categories as $category)
                                        <tr class="category-{{ $category->id }}">
                                            <td>{{ $category->id }}</td>
                                            <td>{{ $category->name }}</td>
                                            <td><img class="category-img" src="../img/categories/{{ $category->img }}" alt=""></td>
                                            <td>{{ $category->updated_at }}</td>
                                            <td>
                                                <button type="button" class="btn btn-danger waves-effect waves-light btn-category" data-toggle="modal" data-target="#delete" data-id="{{ $category->id }}"><i class="fas fa-trash"></i></button>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                            <div class="modal fade" id="delete">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h4 class="modal-title">Delete category</h4>
                                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                                        </div>
                                        <div class="modal-body">
                                            Do you want really to delete this category?
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                            <button type="submit" class="btn btn-red delete-category" data-id="">Delete</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="modal fade" id="add">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <form  action="{{ route('category.store') }}" method="POST" enctype="multipart/form-data">
                                            <div class="modal-header card-header-success">
                                                <h4 class="modal-title">Add Category</h4>
                                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                            </div>
                                            {{ csrf_field() }}
                                            <div class="modal-body">
                                                <div class="{{ $errors->has('category-name') ? ' has-error' : '' }}">
                                                    <label for="category-name">Name Category:</label>
                                                    <input type="text" class="form-control text-capitalize" id="category-name" name="category-name" value="{{ old('name') }}">

                                                    @if ($errors->has('category-name'))
                                                        <span class="help-block">
                                                            <strong>{{ $errors->first('category-name') }}</strong>
                                                        </span>
                                                    @endif

                                                </div>

                                                <div class="{{ $errors->has('category-img') ? ' has-error' : '' }}">
                                                    <label for="category-img">Image:</label>
                                                    <input type="file" class="form-control" id="category-img" name="category-img">

                                                    @if ($errors->has('category-img'))
                                                        <span class="help-block">
                                                            <strong>{{ $errors->first('category-img') }}</strong>
                                                        </span>
                                                    @endif

                                                </div>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="submit" class="btn btn-red" >Add</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')


@endsection

resources/views/admin/comments.blade.php
@extends('layouts.admin')

@section('content')
    <div class="col-9">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header card-header-info">
                        <h4 class="card-title mt-0">Users Table</h4>
                        <p class="card-category"> Here is a subtitle for this table</p>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table">
                                <thead class=" text-primary">
                                <th>
                                    ID
                                </th>
                                <th>
                                    User
                                </th>
                                <th>
                                    Post ID
                                </th>
                                <th>
                                    Parent ID
                                </th>
                                <th>
                                    Comment
                                </th>
                                <th>
                                    Data
                                </th>
                                <th>
                                    Childs count
                                </th>
                                <th>
                                    Delete
                                </th>
                                </thead>
                                <tbody>
                                @foreach($comments as $comment)
                                    <tr @if(Auth::user()->id == $comment->author_id)class="table-active" @endif>
                                        <td>{{ $comment->id }}</td>
                                        <td>{{ $comment->users->name}}  {{ $comment->users->surname}}</td>
                                        <td>{{ $comment->post_id }}</td>
                                        <td>{{ $comment->parent_id }}</td>
                                        <td>{{ $comment->comment }}</td>
                                        <td>{{ $comment->updated_id }}</td>
                                        <td>{{ Count($comment->child)}}</td>
                                        <td>
                                            <button type="button" class="btn btn-danger waves-effect waves-light btn-comment" data-toggle="modal" data-target="#delete" data-id="{{ $comment->id }}"><i class="fas fa-trash"></i></button>
                                        </td>
                                    </tr>
                                @endforeach
                                <div class="modal fade" id="delete">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h4 class="modal-title">Delete post</h4>
                                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                            </div>
                                            <div class="modal-body">
                                                Do you want really to delete this comment?
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                                <button type="submit" class="btn btn-red delete-comment" data-id="">Delete</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    </div>
@endsection

resources/views/admin/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="col-9">
        <p class="welcome text-center margin-30">Welcome {{ Auth::user()->name}} {{ Auth::user()->surname}}</p>
        <div class="row text-center">
            <div class="col-3">
                <div class="blog-progress">
                    <div class="icon">
                        <i class="fas fa-users"></i>
                    </div>
                    <div class="progress-item">
                        <div class="progress-count">{{ count($users) }}</div>
                        <div class="progress-name">users</div>
                        <div class="text">Count of users registered in Amelie </div>
                    </div>
                    <div class="more-info d-inline-block">
                        <div class="btn btn-default ">
                            <a href="{{ url('admin/users') }}">More Info</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-3">
                <div class="blog-progress">
                    <div class="icon">
                        <i class="fas fa-bookmark"></i>
                    </div>
                    <div class="progress-item">
                        <div class="progress-count">{{ count($posts) }}</div>
                        <div class="progress-name">posts</div>
                        <div class="text">Count of posts showed in Amelie </div>
                    </div>
                    <div class="more-info d-inline-block">
                        <div class="btn btn-default ">
                            <a href="{{ url('admin/posts') }}">More Info</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-3">
                <div class="blog-progress">
                    <div class="icon">
                        <i class="fas fa-certificate"></i>
                    </div>
                    <div class="progress-item">
                        <div class="progress-count">{{ count($categories) }}</div>
                        <div class="progress-name">categories</div>
                        <div class="text">Count of categories of posts in Amelie </div>
                    </div>
                    <div class="more-info d-inline-block">
                        <div class="btn btn-default ">
                            <a href="{{ url('admin/categories') }}">More Info</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-3">
                <div class="blog-progress">
                    <div class="icon">
                        <i class="fas fa-comment"></i>
                    </div>
                    <div class="progress-item">
                        <div class="progress-count">{{ count($comments) }}</div>
                        <div class="progress-name">comments</div>
                        <div class="text">Count of comments in posts Amelie </div>
                    </div>
                    <div class="more-info d-inline-block">
                        <div class="btn btn-default ">
                            <a href="{{ url('admin/comments') }}">More Info</a>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>
@endsection

resources/views/admin/posts.blade.php
@extends('layouts.admin')

@section('content')
    <div class="col-9">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header card-header-info">
                        <h4 class="card-title mt-0">Posts Table</h4>
                        <p class="card-category"> Here is a subtitle for this table</p>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table">
                                <thead class=" text-primary">
                                    <th>
                                        ID
                                    </th>
                                    <th>
                                        Author ID
                                    </th>
                                    <th>
                                        Category
                                    </th>
                                    <th>
                                        Title
                                    </th>
                                    <th>
                                        Image
                                    </th>
                                    <th>
                                        Body
                                    </th>
                                    <th>
                                        Date
                                    </th>
                                    <th>
                                        Comment Count
                                    </th>
                                    <th>
                                        Delete
                                    </th>
                                </thead>
                                <tbody>
                                @foreach($posts as $post)
                                    <tr @if(Auth::user()->id == $post->author_id)class="table-active" @endif>
                                        <td>{{ $post->id }}</td>
                                        <td>{{ $post->author_id }}</td>
                                        <td>{{ $post->category->name }}</td>
                                        <td>{{ str_limit($post->title, 20) }}</td>
                                        <td><img src="../img/posts/{{ $post->img }}" alt="Post img" class="admin-post-img"></td>
                                        <td>{{ str_limit($post->body, 20) }}</td>
                                        <td>{{ $post->updated_at }}</td>
                                        <td><a href="#">{{ count($post->comment) }}</a></td>
                                        <td>
                                            <button type="button" class="btn btn-danger waves-effect waves-light btn-post" data-toggle="modal" data-target="#delete" data-id="{{ $post->id }}"><i class="fas fa-trash"></i></button>
                                        </td>
                                    </tr>
                                @endforeach
                                <div class="modal fade" id="delete">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h4 class="modal-title">Delete post</h4>
                                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                            </div>
                                            <div class="modal-body">
                                                Do you want really to delete this post?
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                                <button type="submit" class="btn btn-red delete-post" data-id="">Delete</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users.blade.php
@extends('layouts.admin')

@section('content')
    <div class="col-9">
        <div class="row">
            <div class="col-12">
                <div class="card">
                        <div class="card-header card-header-primary" data-background-color="purple">
                            <h4 class="card-title mt-0">Users Table</h4>
                            <p class="card-category"> Here is a subtitle for this table</p>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead class=" text-primary">
                                    <th>
                                        ID
                                    </th>
                                    <th>
                                        Name
                                    </th>
                                    <th>
                                        Surname
                                    </th>
                                    <th>
                                        Email
                                    </th>
                                    <th>
                                        Phone
                                    </th>
                                    <th>
                                        Avatar
                                    </th>
                                    <th>
                                        Posts count
                                    </th>
                                    <th>
                                        Admin
                                    </th>
                                    </thead>
                                    <tbody>
                                        @foreach($users as $user)
                                            <tr @if(Auth::user()->id == $user->id)class="table-active" @endif>
                                                <td>{{ $user->id }}</td>
                                                <td>{{ $user->name }}</td>
                                                <td>{{ $user->surname }}</td>
                                                <td>{{ $user->email }}</td>
                                                <td>{{ $user->phone }}</td>
                                                <td><img src="../img/users/{{ $user->avatar }}" alt="User avatar" class="user-img"></td>
                                                <td><a href="{{ route('user.show',$user->id) }}">{{ count($user->posts) }}</a></td>
                                                <td><input type="checkbox" id="switch-{{$user->id}}"  name="set-name" class="switch-input" @if($user->is_admin == 1) checked @endif data-id="{{$user->id}}">
                                                    <label for="switch-{{$user->id}}" class="switch-label" ></label>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                </div>
            </div>
                </div>
            </div>
        </div>
    </div>
@endsection