routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/get-posts', 'HomeController@getPosts');
Route::get('confirm/{token}/{email}','UserController@index');
Route::post('user/change-password','UserController@changePassword');
Route::resource('user', 'UserController');


Route::get('redirect', 'SocialAuthFacebookController@redirect');
Route::get('callback', 'SocialAuthFacebookController@callback');

Route::get('/get-url','PostController@getURL');
Route::post('/post/{id}','PostController@updatePost');
Route::resource('post', 'PostController');
Route::resource('category', 'CategoryController');

Route::get('all-comments/{post}', 'CommentController@showComments');
Route::resource('comments', 'CommentController');

Route::prefix('admin')->group(function () {
    Route::get('/', 'AdminController@index');
    Route::get('notification', 'AdminController@notification');
    Route::get('users', 'AdminController@users');
    Route::get('update-admin', 'AdminController@updateAdmin');
    Route::get('posts', 'AdminController@posts');
    Route::get('categories', 'AdminController@categories');
    Route::get('comments', 'AdminController@comments');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use App\Notifications\SendEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token'
    ];

    public function posts()
    {
        return $this->hasMany('App\Post', 'author_id', 'id');
    }

    public function comments()
    {
        return $this->hasMany('App\Comment','user_id','id');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;


use App\Post;
use App\User;
use Illuminate\Http\File;
use App\Http\Requests\UpdatePostRequest;
use App\Http\Requests\ChangePasswordRequest;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index($token, $email)
    {


//        $this->email = $email;
//        $this->token = $token;
//        $user = new User;
//        dd($user);
//        if($user->email == $email && $user->token == $token){
//
//        };
        return view('home');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
//        if ($id == Auth::user()->id) {
//            return redirect()->route('post.index');
//        } else {
            $user = User::find($id)->load('posts.category', 'posts.comments', 'posts.user');
//            $posts = Post::where('author_id', $id)->get()->load('category', 'user');
            return response()->json($user);
//        }

    }

    public function edit()
    {
        return view('user.update');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePostRequest $request, $id)
    {
        $user_old_data = User::find($id);
        $user_data = $request->all();
        if ($request->hasFile('avatar')) {
            if ($user_old_data->avatar != 'default-avatar.png') {
                File::delete(public_path('img/users/' . $user_old_data->avatar));
            }
            $name = $request->file('avatar')->hashName();
            $move = $request->file('avatar')->move('img/users', $name);
            if ($move) {
                $avatar = $name;
            }
        } else {
            $avatar = $user_old_data->avatar;
        }
        $data = [
            'name' => $user_data['name'],
            'surname' => $user_data['surname'],
            'email' => $user_data['email'],
            'phone' => $user_data['phone'],
            'avatar' => $avatar
        ];
        $update = User::find($id)->update($data);

        if ($update) {
            return redirect()->back()->with('status', 'user-settings');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    /**
     * Change password logged in user
     *
     * @param  input
     * @return \Illuminate\Http\Response
     */

    public function changePassword(ChangePasswordRequest $request)
    {
        $user = Auth::user();
        $old = $request['current-password'];
        $new = $request['new-password'];
        if (!(Hash::check($old, $user['password']))) {
            // The passwords matches
            return redirect()->back()->with("status", "password-matches");
        };
        if (strcmp($old, $new) == 0) {
            //Current password and new password are same
            return redirect()->back()->with("status", "password-error");
        };
        //Change Password
        $user['password'] = bcrypt($old);
        $user->save();
        return redirect()->back()->with("status", "password-changed");
    }
}

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')
    <section id="my-post">
        <div class="theme-menu post">
            <div class="container text-center padding-45">
                <div class="my d-inline">
                    My Post
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">

                @foreach($posts as $post)
                    <div class="card col-4">
                        <div class="card-post">
                            <div class="card-header">
                                <img class="card-img-top" src="/img/posts/{{ $post['img'] }}" alt="Card image"
                                     style="width:100%">
                            </div>
                            <div class="card-body">
                                <div>
                                    <h3 class="card-title d-inline-block">{{ $post['title'] }}</h3>
                                    <a class="post-title-a" href="{{ route('category.show',$post['category']['id']) }}">{{ $post['category']['name'] }}</a>
                                </div>
                                <div>
                                    <a href="{{ route('user.show',$post['author_id']) }}"> {{ $post['user']['name'] }} {{ $post['user']['surname'] }}</a>
                                </div>
                                <div>
                                    <p class="card-text">{{ $post['body'] }}</p>
                                </div>
                                <div>
                                    @if($post['author_id'] == Auth::user()->id)
                                        <a href="{{ route('post.show', $post['id']) }}" class="btn-red float-right">Read
                                            more</a>
                                        <a href="{{ route('post.edit', $post['id']) }}" class="btn-red float-right">Edit</a>
                                        <form action="{{ route('post.destroy', $post['id']) }}" method="POST"
                                              enctype="multipart/form-data">
                                            {{ method_field('DELETE') }}
                                            {{ csrf_field() }}
                                            <input type="submit" class="btn btn-red" value="Delete">
                                        </form>
                                    @else
                                        <a href="{{ route('post.show', $post['id']) }}" class="btn-red float-right">Read
                                            more</a>
                                    @endif
                                </div>

                            </div>
                            <div class="data d-flex justify-content-around">
                                <div class="time">
                                    <i class="far fa-clock"></i>
                                    <span>{{ $post['created_at'] }}</span>
                                </div>
                                <div class="comments">
                                    <i class="fas fa-comment"></i>
                                    <span></span> Comment
                                </div>
                                <div class="likes">
                                    <i class="fas fa-heart"></i>
                                    <span></span>
                                </div>
                            </div>
                            <div class="card-footer">
                                <div class="follow d-flex justify-content-around">
                                    <i class="fab fa-instagram"></i>
                                    <i class="fab fa-facebook-f"></i>
                                    <i class="fab fa-twitter"></i>
                                    <i class="fab fa-google-plus-g"></i>
                                </div>
                            </div>
                        </div>
                    </div>

                @endforeach
            </div>
        </div>
    </section>

@endsection

resources/views/user/update.blade.php
@extends('layouts.app')

@section('content')
    {{--@if (session('status'))--}}
        <div class="alert-div {{ session('status') }}">
        </div>
    {{--@endif--}}
    <section id="edit-account">
        <div class="theme-menu post">
            <div class="container text-center padding-45">
                <div class="add d-inline">
                    Account settings
                </div>
            </div>
        </div>
        <div class="container padding-30 margin-30">
            <form class="form-horizontal" method="POST" action="{{ route('user.update',Auth::user()->id) }}" enctype="multipart/form-data">
                <input name="_method" type="hidden" value="PUT">
                {{ csrf_field() }}

                <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                    <label for="name" class="col-md-4 control-label">Name</label>
                    <div class="col-md-6">
                        <input id="name" type="text" class="form-control" name="name" value="{{ Auth::user()->name }}" autofocus>
                        @if ($errors->has('name'))
                            <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                        @endif
                    </div>
                </div>

                <div class="form-group{{ $errors->has('surname') ? ' has-error' : '' }}">
                    <label for="surname" class="col-md-4 control-label">Surname</label>

                    <div class="col-md-6">
                        <input id="surname" type="text" class="form-control" name="surname" value="{{ Auth::user()->surname}}"autofocus>

                        @if ($errors->has('surname'))
                            <span class="help-block">
                                        <strong>{{ $errors->first('surname') }}</strong>
                                    </span>
                        @endif
                    </div>
                </div>

                <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                    <label for="email" class="col-md-4 control-label">E-Mail Address</label>
                    <div class="col-md-6">
                        <input id="email" type="email" class="form-control" name="email" value="{{ Auth::user()->email }}">
                        @if ($errors->has('email'))
                            <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                        @endif
                    </div>
                </div>

                <div class="form-group{{ $errors->has('phone') ? ' has-error' : '' }}">
                    <label for="name" class="col-md-4 control-label">Phone</label>
                    <div class="col-md-6">
                        <input id="phone" type="text" class="form-control" name="phone" value="{{ Auth::user()->phone }}" autofocus>
                        @if ($errors->has('phone'))
                            <span class="help-block">
                                        <strong>{{ $errors->first('phone') }}</strong>
                                    </span>
                        @endif
                    </div>
                </div>

                <div class="form-group{{ $errors->has('avatar') ? ' has-error' : '' }}">
                    <label for="avatar" class="col-md-4 control-label">Avatar</label>
                    <div class="col-md-6">
                        <input id="avatar" type="file" class="form-control" name="avatar" >
                        @if ($errors->has('avatar'))
                            <span class="help-block">
                                        <strong>{{ $errors->first('avatar') }}</strong>
                                    </span>
                        @endif
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-6 col-md-offset-4">
                        <a class="btn btn-default" data-toggle="modal" data-target="#myModal">Change Password</a>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-6 col-md-offset-4">
                        <button type="submit" class="btn btn-red">
                            Save
                        </button>
                    </div>
                </div>
            </form>
            <div class="modal fade" id="myModal">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Change password</h4>
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>

                        <form action="{{ url('user/change-password') }}" method="post" enctype="multipart/form-data">
                            <div class="modal-body">
                                {{ csrf_field() }}
                                <div class="form-group{{ $errors->has('current-password') ? ' has-error' : '' }}">
                                    <label for="new-password" class="col-md-4 control-label">Current Password</label>

                                    <div class="col-md-6">
                                        <input id="current-password" type="password" class="form-control" name="current-password" required>

                                        @if ($errors->has('current-password'))
                                            <span class="help-block">
                                        <strong>{{ $errors->first('current-password') }}</strong>
                                    </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group{{ $errors->has('new-password') ? ' has-error' : '' }}">
                                    <label for="new-password" class="col-md-4 control-label">New Password</label>

                                    <div class="col-md-6">
                                        <input id="new-password" type="password" class="form-control" name="new-password" required>

                                        @if ($errors->has('new-password'))
                                            <span class="help-block">
                                        <strong>{{ $errors->first('new-password') }}</strong>
                                    </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="new-password-confirm" class="col-md-4 control-label">Confirm New Password</label>

                                    <div class="col-md-6">
                                        <input id="new-password-confirm" type="password" class="form-control" name="new-password_confirmation" required>
                                    </div>
                                </div>
                            </div>

                            <div class="modal-footer">
                                <button class="btn btn-red" id="change-password">Change</button>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection